[package]
name = "musicfs-fuse"
version.workspace = true
edition.workspace = true

[dependencies]
musicfs-core = { path = "../musicfs-core" }
musicfs-cache = { path = "../musicfs-cache" }
musicfs-cas = { path = "../musicfs-cas" }
fuser.workspace = true
tokio.workspace = true
tracing.workspace = true
libc = "0.2"
