[package]
name = "musicfs-grpc"
version.workspace = true
edition.workspace = true

[dependencies]
musicfs-search = { path = "../musicfs-search" }
musicfs-core = { path = "../musicfs-core" }
tonic.workspace = true
prost.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true

[build-dependencies]
tonic-build.workspace = true

[dev-dependencies]
tempfile.workspace = true
