[package]
name = "musicfs-cas"
version.workspace = true
edition.workspace = true

[features]
default = []
failpoints = ["fail/failpoints"]

[dependencies]
fail = { workspace = true, optional = true }
musicfs-core = { path = "../musicfs-core" }
musicfs-origins = { path = "../musicfs-origins" }
musicfs-sync = { path = "../musicfs-sync" }
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
sled.workspace = true
xxhash-rust.workspace = true
bytes.workspace = true
rmp-serde.workspace = true
hex.workspace = true
dirs.workspace = true
thiserror.workspace = true
parking_lot.workspace = true

[dev-dependencies]
tempfile.workspace = true
musicfs-cache = { path = "../musicfs-cache" }
