[package]
name = "musicfs-core"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tokio = { workspace = true, features = ["sync"] }
xxhash-rust.workspace = true
hex.workspace = true

[dev-dependencies]
tempfile.workspace = true
