[package]
name = "musicfs-origins"
version.workspace = true
edition.workspace = true

[dependencies]
musicfs-core = { path = "../musicfs-core" }
async-trait.workspace = true
dashmap.workspace = true
tokio = { workspace = true, features = ["fs", "sync", "time"] }
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
